# Generated by Django 5.2.1 on 2025-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_cartitem_user_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
