# Generated by Django 5.2.1 on 2025-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Мужчинам'), ('women', 'Женщинам')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
