# Generated by Django 5.2.1 on 2025-05-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Мужчинам'), ('women', 'Женщинам')], max_length=10, null=True),
        ),
    ]
